## Script to calculate the CI index values from rrs values
## generated by the NOAA EXE program
## The files with the rrs data are named "Seabass" from the NOAA EXE program
## a TSV file is then written with the CI values
## CI value calculated using equation 1 in Wynne et al. 2008

## Modified CI and pixel values (0-250) calculated based on equations provided
## by Randy Turner at SFEI. A pixel value of 0 (or NaN in the equation) is the background CI value level.

## CI to pixel value: CI=10^(3/250*Pix_val-4.2)
## CI to modified CI: CI_mod= CI * 15805.18
## rrs= remote sensed reflectance

## Field CI values are then merged with the satellite pixel values (0-250)
## The location of the sample pixels is determined through maps generated in the file, map_sample_pixel_numbers.R\
## The results are stored in: Data/Sentinel_flyover_data/sample_pixel_numbers.tsv


## in_dir= Pathway to output of NOAA EXE program rrs files
## out_path= path and filename for exported .tsv file with CI values

calc_CI_values <- function(in_dir, out_path){
  require(tidyverse)

## Read in rrs files
rrs_files <- list.files(in_dir)
sample_IDs <-  str_replace(rrs_files, ".txt", "") %>% str_replace(., "rrs-", "")

rrs_list <- map(rrs_files, function(x) suppressMessages(read_csv(file.path(in_dir, x), 
                                                skip= 31, 
                                                col_names = FALSE)) %>% 
                  rename(nm= X1, rrs= X2))

## FILTER WAVELENGTHS TO MATCH OLCI BANDS: 620, 665, 681, AND 709
extract_olci_bands <- function(rrs_file){
  require(tidyverse)

  ## OLCI BANDS
  olci <- data.frame(band= c("b07_620", "b08_665", "b10_681", "b11_709"),
                     center=  c(620, 665, 681, 709),
                     width= c(10, 10, 7.5, 10),
                     stringsAsFactors = FALSE) %>% 
    mutate(min= center - width/2,
           max= center + width/2)
  
  
  ## FILTER SPECTRA BY OLCI BANDS
  spec_olci_bands <- do.call(rbind, apply(olci, 1, 
                                          function(x){
                                            rrs_file %>% 
                                              filter(nm >= x["min"] & nm <= x["max"]) %>% 
                                              mutate(band= x["band"])
                                          }))
  
  ## AVERAGE OLCI BAND WIDTHS TOGETHER
  spec_olci_means <- spec_olci_bands %>% 
    group_by(band) %>% 
    summarize(rrs_avg= mean(rrs, na.rm= TRUE),
              sd= sd(rrs, na.rm= TRUE)) %>% 
    rename(rrs= rrs_avg)
  return(spec_olci_means)
  
}

olci_band_list <- map(rrs_list, extract_olci_bands)
names(olci_band_list) <- sample_IDs


## CALCULATE CYANOBACTERIAL INDEX
## From Wynne et al. 2008

calc_CI <- function(df){
  
  df.wide <- df %>% 
    select(-sd) %>% 
    spread(band, rrs)
  
  # Wynne et al. 2008 equation #1
  CI= with(df.wide,
           -1*(b10_681 - b08_665 - (b11_709 - b08_665)*((681-665)/(709-665)))
  )
  return(CI)
}

ci_list <- map(olci_band_list, calc_CI)
names(ci_list) <- sample_IDs


# Make into a dataframes
rrs_bands_df <- do.call(rbind, olci_band_list) %>% cbind(rep(names(olci_band_list), each= 4), .) %>% as_tibble()
names(rrs_bands_df)[1] <- "uniqueID"

rrs_bands_df <- rrs_bands_df %>% 
  mutate(waterbody= do.call(rbind, str_split(uniqueID, "-"))[, 1], 
         sample= do.call(rbind, str_split(uniqueID, "-"))[, 2]) %>% 
  mutate(site= do.call(rbind, str_split(sample, "_"))[, 1],
         rep= do.call(rbind, str_split(sample, "_"))[, 2]) %>% 
  select(uniqueID, waterbody, sample, site, rep, band, rrs, sd) 


ci_df <- tibble(uniqueID= names(ci_list), ci= do.call(rbind, ci_list)[, 1]) %>% 
  mutate(waterbody= do.call(rbind, str_split(uniqueID, "-"))[, 1], 
         sample= do.call(rbind, str_split(uniqueID, "-"))[, 2]) %>% 
  mutate(site= do.call(rbind, str_split(sample, "_"))[, 1],
         rep= do.call(rbind, str_split(sample, "_"))[, 2]) %>% 
  select(uniqueID, waterbody, sample, site, rep, ci) 
  
# Calc modified CI and pixel values
ci_df <- ci_df %>% 
  mutate(ci_mod= ci * 15805.18,
         pix_val= (log10(ci)+4.2)/0.012) %>% 
  mutate(pix_val= ifelse(is.na(pix_val), 0, pix_val)) %>% 
  mutate(pixel= str_replace(site, "S[0-9]", ""))


# Write files
write_tsv(rrs_bands_df, path= file.path(out_path, "rrs_OLCI_band_values.tsv"))
write_tsv(ci_df, path= file.path(out_path, "CI_field.tsv"))
return(ci_df)
}


#field_CI_values <- calc_CI_values(in_dir = "Data/rrs_data", out_path = "Data") 


## JOIN SATELLITE AND FIELD CI VALUES
# satellite_dir <- "Data/Sentinel_flyover_data"
# sample_pixels <-  read_tsv("Data/Sentinel_flyover_data/sample_pixel_numbers.tsv")

join_sat_field_CI <- function(sat_dir, CI_field_df, samp_pixs, out_path, writeFile= TRUE){
  
  ## Read in Sentinel satellite data
  make_satellite_data_list <- function(in_dir){
    sat_files <- list.files(in_dir, pattern= "*.csv")
    
    sat_list <- map(sat_files, function(x) read_csv(file.path(in_dir, x)) %>% 
                      rename(pix_val_sat= `Pixel Value`))
    names(sat_list) <- str_replace(sat_files, "sentinel-", "") %>% str_replace(., ".csv", "")
    
    # Add waterbody and pixel number column
    sat_list <- map2(sat_list, names(sat_list), function(df, name) mutate(df, waterbody= name,
                                                                          pix_num= seq(1, length(df$pix_val_sat))))
    return(sat_list)
  }
  sat_list <- make_satellite_data_list(in_dir = sat_dir)
  
  
  ## Extract sample pixels from satellite data files
  extract_sample_pixels <- function(satellite_list, samp_pixs, waterbodyID){
    samp_pix_filt <- samp_pixs %>% 
      filter(waterbody == waterbodyID)
    
    waterbody_df <- satellite_list[[waterbodyID]]
    
    extracted_pixels <- waterbody_df %>% 
      filter(waterbody_df$pix_num %in% samp_pix_filt$pix_num) %>% 
      left_join(., samp_pixs) 
    return(extracted_pixels)
  }
  
  sat_samp_pixs <- map(names(sat_list), function(x) extract_sample_pixels(satellite_list = sat_list, samp_pixs= samp_pixs, waterbodyID = x)) %>% 
    do.call(rbind, .)
  
  ## Calculate modified CI values
  sat_samp_pixs <- sat_samp_pixs %>% 
    mutate(ci_sat= 10^(3/250*pix_val_sat-4.2),
           ci_mod_sat= ci_sat*15805.18)
  
  
  ## Join satellite and field data frames
  ci_values <- left_join(sat_samp_pixs, CI_field_df, by= c("waterbody", "pixel")) %>% 
    rename(pix_site= site) %>% 
    mutate(site= str_replace(pix_site, "P[0-9]", ""))
  
  if(writeFile == TRUE){
    write_tsv(ci_values, path= file.path(out_path, "CI_field_sat.tsv"))
  }
  return(ci_values)
}

# CI_field_sat <- join_sat_field_CI(sat_dir = satellite_dir, 
#                                   CI_field_df = field_CI_values, 
#                                   samp_pixs = sample_pixels, 
#                                   out_path = "Data")

join_CI_with_water_data <- function(ci_df, h2o_tsv_file, writeFile= TRUE, out_path){
  require(tidyverse)
  require(lubridate)  
# Read in h2o sample data (e.g. chla, secchi, turbidity, etc.)
h2o_df <- read_tsv(h2o_tsv_file) %>% 
  mutate(secchi_avg= (secchi_disappear_m + secchi_reappear_m)/2) %>% 
  mutate(pix_site= str_c(pixel, site),
         date= dmy(date))

# Merge CI data with h2o Data 
  ci_h2o_df <- left_join(ci_df, h2o_df) %>% 
    select(-Lon, -Lat) %>% 
    select(waterbody, date, uniqueID, lat, long, pixel, site, pix_site, sample, rep, pix_num, ci, ci_mod, pix_val, ci_sat, ci_mod_sat, pix_val_sat, everything())
  
  if(writeFile == TRUE){
    write_tsv(ci_h2o_df, path= file.path(out_path, "CI_field_sat_h2o_data.tsv"))
  }
  return(ci_h2o_df)
}



