## Script to calculate the CI index values from rrs values
## generated by the NOAA EXE program
## The files with the rrs data are named "Seabass" from the NOAA EXE program
## a TSV file is then written with the CI values
## CI value calculated using equation 1 in Wynne et al. 2008

## Modified CI and pixel values (0-250) calculated based on equations provided
## by Randy Turner at SFEI. A pixel value of 0 (or NaN in the equation) is the background CI value level.

## CI to pixel value: CI=10^(3/250*Pix_val-4.2)
## CI to modified CI: CI_mod= CI * 15805.18
## rrs= remote sensed reflectance

## Field CI values are then merged with the satellite pixel values (0-250)
## The location of the sample pixels is determined through maps generated in the file, map_sample_pixel_numbers.R\
## The results are stored in: Data/Sentinel_flyover_data/sample_pixel_numbers.tsv


## in_dir= Pathway to output of NOAA EXE program rrs files
## out_path= path and filename for exported .tsv file with CI values


## Load functions
source("Scripts/calc_CI_functions.R")

## CALC CI VALUS FROM RADIOMETER RRS DATA
field_CI_values <- calc_CI_values(in_dir = "Data/rrs_data", out_path = "Data") 



## JOIN SATELLITE AND FIELD CI VALUES
satellite_dir <- "Data/Sentinel_flyover_data"
sample_pixels <-  read_tsv("Data/Sentinel_flyover_data/sample_pixel_numbers.tsv")


CI_field_sat <- join_sat_field_CI(sat_dir = satellite_dir, 
                                  CI_field_df = field_CI_values, 
                                  samp_pixs = sample_pixels, 
                                  out_path = "Data", 
                                  writeFile= TRUE)

## JOIN WITH WATER SAMPLE DATA
ci_h2o_df <- join_CI_with_water_data(ci_df = CI_field_sat, 
                                     h2o_tsv_file = "Data/field_Data_satellite_2019.txt", 
                                     writeFile= TRUE, 
                                     out_path= "Data")
