## Script to calculate the CI index values from rrs values
## generated by the NOAA EXE program
## a TSV file is then written with the CI values
## CI value calculated using equation 1 in Wynne et al. 2008


## The files with the rrs data are named "Seabass" from the NOAA EXE program
## rrs= remote sensed reflectance

## in_dir= Pathway to output of NOAA EXE program rrs files
## out_path= path and filename for exported .tsv file with CI values

write_CI_values <- function(in_dir, out_path){
  require(tidyverse)

## Read in rrs files
rrs_files <- list.files(in_dir)
sample_IDs <-  str_replace(rrs_files, ".txt", "") %>% str_replace(., "rrs-", "")

rrs_list <- map(rrs_files, function(x) suppressMessages(read_csv(file.path(rrs_dir, x), 
                                                skip= 31, 
                                                col_names = FALSE)) %>% 
                  rename(nm= X1, rrs= X2))

## FILTER WAVELENGTHS TO MATCH OLCI BANDS: 620, 665, 681, AND 709
extract_olci_bands <- function(rrs_file){
  require(tidyverse)
  
  ## OLCI BANDS
  olci <- data.frame(band= c("b07_620", "b08_665", "b10_681", "b11_709"),
                     center=  c(620, 665, 681, 709),
                     width= c(10, 10, 7.5, 10),
                     stringsAsFactors = FALSE) %>% 
    mutate(min= center - width,
           max= center + width)
  
  
  ## FILTER SPECTRA BY OLCI BANDS
  spec_olci_bands <- do.call(rbind, apply(olci, 1, 
                                          function(x){
                                            rrs_file %>% 
                                              filter(nm >= x["min"] & nm <= x["max"]) %>% 
                                              mutate(band= x["band"])
                                          }))
  
  ## AVERAGE OLCI BAND WIDTHS TOGETHER
  spec_olci_means <- spec_olci_bands %>% 
    group_by(band) %>% 
    summarize(rrs_avg= mean(rrs, na.rm= TRUE),
              sd= sd(rrs, na.rm= TRUE)) %>% 
    rename(rrs= rrs_avg)
  return(spec_olci_means)
  
}

olci_band_list <- map(rrs_list, extract_olci_bands)
names(olci_band_list) <- sample_IDs


## CALCULATE CYANOBACTERIAL INDEX
## From Wynne et al. 2008

calc_CI <- function(df){
  
  df.wide <- df %>% 
    select(-sd) %>% 
    spread(band, rrs)
  
  # Wynne et al. 2008 equation #1
  CI= with(df.wide,
           -1*(b10_681 - b08_665 - (b11_709 - b08_665)*((681-665)/(709-665)))
  )
  return(CI)
}

ci_list <- map(olci_band_list, calc_CI)
names(ci_list) <- sample_IDs


# Make into a dataframe
# ci_df <- tibble(uniqueID= names(ci_list), ci= do.call(rbind, ci_list)[, 1]) %>% 
#   mutate(waterbody= do.call(rbind, str_split(uniqueID, "-"))[, 1], 
#          sample= do.call(rbind, str_split(uniqueID, "-"))[, 2]) %>% 
#   mutate(pix_site= do.call(rbind, str_split(sample, "_"))[, 1],
#          rep= do.call(rbind, str_split(sample, "_"))[, 2]) %>% 
#   mutate(pixel= str_sub(pix_site, start= 1, end= 2),
#          site= str_sub(pix_site, start= 3, end= 4)) %>% 
#   select(uniqueID, waterbody, sample, pix_site, pixel,site, rep, ci)

ci_df <- tibble(uniqueID= names(ci_list), ci= do.call(rbind, ci_list)[, 1]) %>% 
  mutate(waterbody= do.call(rbind, str_split(uniqueID, "-"))[, 1], 
         sample= do.call(rbind, str_split(uniqueID, "-"))[, 2]) %>% 
  mutate(site= do.call(rbind, str_split(sample, "_"))[, 1],
         rep= do.call(rbind, str_split(sample, "_"))[, 2]) %>% 
  select(uniqueID, waterbody, sample, site, rep, ci)


# Write file
write_tsv(ci_df, path= out_path)
}


write_CI_values(in_dir = "Data/rrs_data", out_path = "Data/CI_values.tsv")
