## Script to prepare radiometer data for use with the NOAA scripts
## to calculate remote sensed reflectance values

## KBG Sept-2019

## Load functions
source("Scripts/radiometer_noaa_format_functions.R")
library(tidyverse)

## WATERBODY: Lake San Antonio
## SAMPLING DATE: 01-Aug-2019

## Specify pathways
base_dir <- "Data/20190801_LakeSanAntonio"
metadata_file <- file.path(base_dir, "radiometer_LakeSanAntonio_20190801.txt")
spectra_out_dir <- file.path(base_dir, "spectra_out")
ascii_dir <- file.path(base_dir, "ascii_export")
noaa_out_dir <- file.path(base_dir, "noaa_files")
rrs_dir <- "Data/rrs_data"
sampleName <- "LakeSanAntonio_20190801"



#### PROCESSING WORKFLOW BELOW ####


# Function to format metadata from Radiometer Fieldsheets
# this returns a dataframe with metadata for every file generated
# by the radiometer
# Arguments:
# file_path: the location and filename of the radiometer field data
meta_df <- format_radiometer_metadata(metadata_file_path= metadata_file)

# Exports a single text file for each pixel, site, spectra_rep
# includes metadata and files associated with that measurement
# Arguments:
# metadata_df: the data frame generated by format_radiometer_metadata
# export_path: a folder to store output (will create folder if it does not exist)
export_spectra_files(metadata_df= meta_df, 
                     export_path= spectra_out_dir)

# Function to export plots of the raw radiance values from the radiometer
# Plots are exported to the same folder as the output of export_spectra_files
# Arguments:
# spectra_path: the location of the files exported by export_spectra_files (figures are exported here too)
# ascii_path: the location of the ascii exported files from the radiometer
make_spectra_plots(spectra_path= spectra_out_dir, 
                   ascii_path= ascii_dir)


#### GO THROUGH ALL PLOTS AND FILL OUT THE THE TYPE_REP FILE
# TO DETERMINE WHICH TYPE_REPS WILL BE RETAINED FOR FURTHER ANALYSES
# SAVE THE FILE IN THE SPECTRA_OUT_DIR
# ONCE THE TEXT FILE HAS BEEN CREATED, LOAD IT INTO R BELOW


# Path to file for type_reps to keep in analyses
# (should be saved in the spectra_out_dir)
type_rep_to_keep <- readr::read_tsv(file.path(spectra_out_dir, "type_rep_keep.txt"))


# Create text files formated for the NOAA script. 
# Each file contains a column for the ascii filenames and indicates if 
# it is a plate, sky, or water measurement
# Arguments:
# metadata_df: the data frame generated by format_radiometer_metadata
# export_path: directory to place files
# keep_tr: file that specifies which type_reps should be kept for analyses
noaa_format_export(metadata_df= meta_df, 
                   export_path= noaa_out_dir, 
                   keep_tr= type_rep_to_keep)


#### WRITE THE BATCH FILE TO RUN THE NOAA PROGRAM TO CALCULATE REMOTE SENSED REFLECTANCE VALUES ####

## Specify pathways
#base_dir <- "Data/20190801_LakeSanAntonio"
#noaa_out_dir <- file.path(base_dir, "noaa_files")
#ascii_dir <- file.path(base_dir, "ascii_export")
#noaa_file_dirs <- list.dirs(noaa_out_dir, full.names= FALSE)[-1]


## Copy files from ascii folder to sample folders (sample_dir)
# selects the ascii files listed in the sample.txt file
# and moves them all into a single sample folder (out_dir/samp_dir)
noaa_file_dirs <- list.dirs(noaa_out_dir, full.names= FALSE)[-1]


map(noaa_file_dirs, function(x) copy_ascii_files(samp_dir= x,
                                                    base_dir= noaa_out_dir,
                                                    ascii_dir = ascii_dir,
                                                    out_dir = noaa_out_dir))


## Write a batch file to run the NOAA EXE file on all samples
## These paths need to be written with a backslash for the Windows batch file

# Location of the NOAA program on the hard drive
exe_file <- "C:\\Users\\KBouma-Gregson\\Documents\\Satellite_CI_index\\satellite_field_verification_git\\Data\\ASD_processing\\test_asd_group.exe"
# Location of the 10% spectralon calibration file
cal_file <- "C:\\Users\\KBouma-Gregson\\Documents\\Satellite_CI_index\\satellite_field_verification_git\\Data\\ASD_processing\\Raphe10percent_Spectralon_10AA01-0517-8337.txt"
# Base path for where all the sample directories are located
basePath <- "C:\\Users\\KBouma-Gregson\\Documents\\Satellite_CI_index\\satellite_field_verification_git\\Data\\20190801_LakeSanAntonio\\noaa_files"


map(noaa_file_dirs, function(x){ write_batch_file(samp_dir = x,
                                           base_path= basePath,
                                           exe_path = exe_file, 
                                           cal_path = cal_file, 
                                           batch_name = "LakeSantAntonio_20190801_batch.txt", 
                                           out_dir = noaa_out_dir)
})



## Move rrs files to a single folder to combine with other samples
sample_dirs <- list.dirs(noaa_out_dir)[-1]

map(sample_dirs, function(x) copy_rrs_files(in_dir = x, 
                                            out_dir= rrs_dir,
                                            sample_name= sampleName))







