## Functions to take radiometer metadata and asd output files 
## and restructure them to be used by the NOAA scripts 
## to calculate the remote sensed reflectance values

## KBG Sept-2019



# Function to format metadata from Radiometer Fieldsheets
# this returns a dataframe with metadata for every file generated
# by the radiometer
# Arguments:
# file_path: the location and filename of the radiometer field data
format_radiometer_metadata <- function(file_path){
  # Read in metadata file
  meta <- suppressMessages(read_tsv(file_path)) %>% 
    rename("file_start"= `file start`, "file_end"= `file end`, "spec_rep"= `spectra rep`, "type_rep"= `type rep`) %>% 
    mutate(file_start_num= as.numeric(file_start),
           file_end_num= as.numeric(file_end),
           notes= ifelse(is.na(notes), "na", notes))
  # Make long to get start and end file numbers in same column
  meta.l <- meta %>% 
    select(-file_start, -file_end) %>% 
    gather(key= start_end, value= file_num, file_start_num:file_end_num) %>% 
    arrange(file_num)
  
  # Fill out the vector between start and end numbers
  fill_df <- data.frame(file_num= full_seq(meta.l$file_num, 1)) %>% as_tibble()
  
  # Join complete vector with metadata and fill in remaining columns
  meta_fill <- left_join(fill_df, meta.l, by= "file_num") %>% 
    select(-start_end) %>% 
    fill(everything()) %>% 
    mutate(spec_file= str_c("Spec", 
                            str_pad(.$file_num, pad= "0", 5),
                            ".asd.txt"),
           spectra_id= str_c(pixel, "_", spec_rep),
           unique_id= str_c(pixel, "_", spec_rep, "_", type, type_rep))
  return(meta_fill)
}


# Exports a single text file for each pixel, site, spectra_rep
# includes metadata and files associated with that measurement
# Arguments:
# metadata_df: the data frame generated by format_radiometer_metadata
# export_path: a folder to store output (will create folder if it does not exist)
export_spectra_files <- function(metadata_df, export_path){
  ## Group into their spectra rep ID files
  spectra_list <- md %>% 
    group_by(spectra_id) %>% #, type) %>% 
    # group_map() loops over group_by() categories and returns a list
    group_map(.tbl=., keep= TRUE,
              .f= ~ mutate(.x, type= ifelse(type == "PL", "plate",
                                            ifelse(type == "WA", "water", "sky"))) %>% 
                select(-file_num))
  
  names(spectra_list) <- (unique(md$spectra_id))
  
  ## Create folder
  if(!dir.exists(export_path)){
    dir.create(export_path)
  }
  
  ## Export elements in spectra list as text files
  map2(spectra_list, names(spectra_list), function(df, nm){
    write_tsv(df, path= str_c(export_path, "/", 
                              nm, 
                              ".tsv"))}
  )
}


# Function to export plots of the raw radiance values from the radiometer
# Plots are exported to the same folder as the output of export_spectra_files
# Arguments:
# spectra_path: the location of the files exported by export_spectra_files (figures are exported here too)
# ascii_path: the location of the ascii exported files from the radiometer
make_spectra_plots <- function(spectra_path, ascii_path){
  require(tidyverse)
  require(ggplot2)
  
  # List files
  spectra_files <- list.files(spectra_path, pattern = "*.tsv")
  
  file <- spectra_files[2]
  for(file in spectra_files){
    
    ## Read in Data frame
    spec.rep.df <- read_tsv(file.path(spectra_dir, file))
    spec.files <-  spec.rep.df$spec_file
    
    # Read in the files to a list
    flist <- lapply(file.path(ascii_path,
                              spec.rep.df$spec_file), 
                    function(x) read_tsv(x, col_names = FALSE, skip= 34))
    names(flist) <- spec.files
    
    
    ## Add filename column to each element in the list
    flist2 <- map2(flist, names(flist), function(df, nm) mutate(df, spec_file= nm))
    ## Transform into data frame
    f.df2 <- do.call(rbind, flist2) %>% 
      rename(nm= X1, value= X2) %>% 
      filter(nm <= 900)
    ## Merge with metadata to enable additional aesthetics when plotting
    f.df3 <- left_join(f.df2, spec.rep.df, by= "spec_file") %>% 
      mutate(type_rep= as.character(type_rep))
    
    
    spec_plot <- ggplot(data= f.df3) +
      geom_line(aes(x= nm, y= value, group=spec_file, color= type_rep)) +
      scale_x_continuous(expand= c(0, 0), limits= c(325, 900)) +
      labs(title= unique(spec.rep.df$spectra_id)) +
      facet_grid(type~., scales= "free_y")
    
    ggsave(spec_plot, filename= file.path(spectra_path, str_c(unique(spec.rep.df$spectra_id), ".jpg")),
           dpi= 300, height= 5, width= 6, units= "in")
  }
}


# Create text files formated for the NOAA script. 
# Each file contains a column for the ascii filenames and indicates if 
# it is a plate, sky, or water measurement
# Arguments:
# metadata_df: the data frame generated by format_radiometer_metadata
# export_path: directory to place files
noaa_format_export <- function(metadata_df, export_path){
  require(tidyverse)
  
  ## Group into their spectra rep ID files
  spectra_list_noaa <- metadata_df %>% 
    group_by(spectra_id) %>% #, type) %>% 
    # group_map() loops over group_by() categories and returns a list
    group_map(.tbl=., keep= TRUE,
              .f= ~ mutate(.x, type= ifelse(type == "PL", "plate",
                                            ifelse(type == "WA", "water", "sky")),
                           num= 0))
  names(spectra_list_noaa) <- (unique(md$spectra_id))
  
  
  
  ## Create export folder
  if(!dir.exists(export_path)){
    dir.create(export_path)
  }
  
  ## Export elements in spectra list as text files in export_path directory
  map2(spectra_list_noaa, names(spectra_list_noaa), function(df, nm){
    
    # Spectra_id with type_rep == 1 and no replicate measurements
    if(nm %in% keep_tr$spectra_id == FALSE){
      df %>%
        select(num, type, spec_file) %>%
        write_delim(.,
                    path= str_c(export_path, "/",
                                nm,
                                ".txt"),
                    delim= " ",
                    col_names = FALSE)
    }
    
    
    # Spectra_id with type_rep > 1 and no replicate measurements
    if(nm %in% keep_tr$spectra_id == TRUE){
      df.filt <- df
      
      # Filter keep_tr_filt by the Spectra_id
      keep_tr_filt <- keep_tr %>% 
        filter(spectra_id == nm)
      
      # Loop for multiple types within a spectra_id
      for(typ in keep_tr_filt$type){
        keep_rep <- filter(keep_tr_filt, type == typ)$keep_type_rep
        
        # Filter to keep only the specified type_rep 
        df.filt <-  df.filt %>% 
          filter(!(type == typ & type_rep != keep_rep))
      }
      
      # Write text file
      df.filt %>% 
        select(num, type, spec_file) %>% 
        write_delim(., 
                    path= str_c(export_path, "/", 
                                nm, 
                                ".txt"),
                    delim= " ",
                    col_names = FALSE)
    }
  })
  
  
}

