## Functions to take radiometer metadata and asd output files 
## and restructure them to be used by the NOAA scripts 
## to calculate the remote sensed reflectance values

## KBG Sept-2019



# Function to format metadata from Radiometer Fieldsheets
# this returns a dataframe with metadata for every file generated
# by the radiometer
# Arguments:
# file_path: the location and filename of the radiometer field data
format_radiometer_metadata <- function(metadata_file_path){
  require(tidyverse)
  
  # Read in metadata file
  meta <- suppressMessages(read_tsv(metadata_file_path)) %>% 
    rename("file_start"= `file start`, "file_end"= `file end`, "spec_rep"= `spectra rep`, "type_rep"= `type rep`) %>% 
    mutate(file_start_num= as.numeric(file_start),
           file_end_num= as.numeric(file_end),
           notes= ifelse(is.na(notes), "na", notes))
  # Make long to get start and end file numbers in same column
  meta.l <- meta %>% 
    select(-file_start, -file_end) %>% 
    gather(key= start_end, value= file_num, file_start_num:file_end_num) %>% 
    arrange(file_num)
  
  # Fill out the vector between start and end numbers
  fill_df <- data.frame(file_num= full_seq(meta.l$file_num, 1)) %>% as_tibble()
  
  # Join complete vector with metadata and fill in remaining columns
  meta_fill <- left_join(fill_df, meta.l, by= "file_num") %>% 
    select(-start_end) %>% 
    fill(everything()) %>% 
    mutate(spec_file= str_c("Spec", 
                            str_pad(.$file_num, pad= "0", 5),
                            ".asd.txt"),
           spectra_id= str_c(pixel, "_", spec_rep),
           unique_id= str_c(pixel, "_", spec_rep, "_", type, type_rep))
  return(meta_fill)
}


# Exports a single text file for each pixel, site, spectra_rep
# includes metadata and files associated with that measurement
# Arguments:
# metadata_df: the data frame generated by format_radiometer_metadata
# export_path: a folder to store output (will create folder if it does not exist)
export_spectra_files <- function(metadata_df, export_path){
  require(tidyverse)
  ## Group into their spectra rep ID files
  spectra_list <- metadata_df %>% 
    group_by(spectra_id) %>% #, type) %>% 
    # group_map() loops over group_by() categories and returns a list
    group_map(.tbl=., keep= TRUE,
              .f= ~ mutate(.x, type= ifelse(type == "PL", "plate",
                                            ifelse(type == "WA", "water", "sky"))) %>% 
                select(-file_num))
  
  names(spectra_list) <- (unique(metadata_df$spectra_id))
  
  ## Create folder
  if(!dir.exists(export_path)){
    dir.create(export_path)
  }
  
  ## Export elements in spectra list as text files
  map2(spectra_list, names(spectra_list), function(df, fname){
    write_tsv(df, path= str_c(export_path, "/", 
                              fname, 
                              ".tsv"))}
  )
}


# Function to export plots of the raw radiance values from the radiometer
# Plots are exported to the same folder as the output of export_spectra_files
# Arguments:
# spectra_path: the location of the files exported by export_spectra_files (figures are exported here too)
# ascii_path: the location of the ascii exported files from the radiometer
make_spectra_plots <- function(spectra_path, ascii_path){
  require(tidyverse)
  require(ggplot2)
  
  # List files
  spectra_files <- list.files(spectra_path, pattern = "*.tsv")
  
 # file <- spectra_files[2]
  for(file in spectra_files){
    
    ## Read in Data frame
    spec.rep.df <- read_tsv(file.path(spectra_path, file))
    spec.files <-  spec.rep.df$spec_file
    
    # Read in the files to a list
    flist <- lapply(file.path(ascii_path,
                              spec.rep.df$spec_file), 
                    function(x) read_tsv(x, col_names = FALSE, skip= 34))
    names(flist) <- spec.files
    
    
    ## Add filename column to each element in the list
    flist2 <- map2(flist, names(flist), function(df, fname) mutate(df, spec_file= fname))
    
    ## Transform into data frame
    f.df2 <- do.call(rbind, flist2) %>% 
      rename(nm= X1, value= X2) %>% 
      filter(nm <= 900) # remove wavelengths >900 nm
    
    ## Merge with metadata to enable additional aesthetics when plotting
    f.df3 <- left_join(f.df2, spec.rep.df, by= "spec_file") %>% 
      mutate(type_rep= as.character(type_rep))
    
    ## Make plot
    spec_plot <- ggplot(data= f.df3) +
      geom_line(aes(x= nm, y= value, group=spec_file, color= type_rep)) +
      scale_x_continuous(expand= c(0, 0), limits= c(325, 900)) +
      labs(title= unique(spec.rep.df$spectra_id)) +
      facet_grid(type~., scales= "free_y")
    
    ggsave(spec_plot, filename= file.path(spectra_path, str_c(unique(spec.rep.df$spectra_id), ".jpg")),
           dpi= 300, height= 5, width= 6, units= "in")
  }
}


# Create text files formated for the NOAA script. 
# Each file contains a column for the ascii filenames and indicates if 
# it is a plate, sky, or water measurement
# Arguments:
# metadata_df: the data frame generated by format_radiometer_metadata
# export_path: directory to place files
# keep_tr: file that specifies which type_reps should be kept for analyses
noaa_format_export <- function(metadata_df, export_path, keep_tr){
  require(tidyverse)
  
  ## Group into their spectra rep ID files
  spectra_list_noaa <- metadata_df %>% 
    group_by(spectra_id) %>% #, type) %>% 
    # group_map() loops over group_by() categories and returns a list
    group_map(.tbl=., keep= TRUE,
              .f= ~ mutate(.x, type= ifelse(type == "PL", "plate",
                                            ifelse(type == "WA", "water", "sky")),
                           num= 0))
  names(spectra_list_noaa) <- (unique(meta_df$spectra_id))
  
  
  
  ## Create export folder
  if(!dir.exists(export_path)){
    dir.create(export_path)
  }
  
  #df= spectra_list_noaa[[1]]
  #fname= names(spectra_list_noaa)[1]
  ## Export elements in spectra list as text files in export_path directory
  map2(spectra_list_noaa, names(spectra_list_noaa), function(df, fname){
    
    # Make directory for files
    if(!dir.exists(file.path(export_path, fname))){
      dir.create(file.path(export_path, fname))
    }
    
    # Spectra_id with type_rep == 1 and no replicate measurements
    if(fname %in% keep_tr$spectra_id == FALSE){
      df %>%
        select(num, type, spec_file) %>%
        write_delim(.,
                    # path= str_c(export_path, "/",
                    #            fname, 
                    #            ".txt"),
                    path= str_c(export_path, "/", fname, "/",
                                fname, 
                                ".txt"),
                    delim= " ",
                    col_names = FALSE)
    }
    
    
    # Spectra_id with type_rep > 1 and no replicate measurements
    if(fname %in% keep_tr$spectra_id == TRUE){
      df.filt <- df
      
      # Filter keep_tr_filt by the Spectra_id
      keep_tr_filt <- keep_tr %>% 
        filter(spectra_id == fname)
      
      # Loop for multiple types within a spectra_id
      for(typ in keep_tr_filt$type){
        keep_rep <- filter(keep_tr_filt, type == typ)$keep_type_rep
        
        # Filter to keep only the specified type_rep 
        df.filt <-  df.filt %>% 
          filter(!(type == typ & type_rep != keep_rep))
      }
      
      # Write text file
      df.filt %>% 
        select(num, type, spec_file) %>% 
        write_delim(., 
                   # path= str_c(export_path, "/",
                    #            fname, 
                    #            ".txt"),
                    path= str_c(export_path, "/", fname, "/",
                                fname, 
                                ".txt"),
                    delim= " ",
                    col_names = FALSE)
    }
  })
  
  
}



## Copy files from ascii folder to sample folders (sample_dir)
## Reads in the files listed in the NOAA formatted .txt file
copy_ascii_files <- function(base_dir, samp_dir, ascii_dir, out_dir){
  require(tidyverse)
  
  # Read file and extract the ascii file names
  ascii_files <- read_delim(file.path(base_dir, samp_dir, str_c(samp_dir, ".txt")), 
                            delim= " ", 
                            col_names= FALSE) %>% 
    select(X3) %>% 
    pull()
  
  # Copy ascii files into the sample folder
  file.copy(from= file.path(ascii_dir, ascii_files), to= file.path(out_dir, samp_dir))
 
  
  # The file.copy() is rather slow above. I tested an alternate method using system2 below
  # but it was also slow, so I am keeping file.copy() becaus the code is easier to understand.
  
  # file_paths <- gsub("/", "\\", file.path(ascii_dir, ascii_files), fixed= TRUE)
  # windows_out_dir <- gsub("/", "\\", file.path(out_dir, samp_dir), fixed= TRUE)
  # map(file_paths,  function(x) system2('xcopy', args= c(x, windows_out_dir)))
  # 
}




### Write the NOAA EXE batch file
## Changes the directory to the location of the ascii files and the .txt file
## Then it writes the Windows command prompt to run the EXE function for producing remote sense reflectance values
## Outputs a text file with the command for every sample in the directory
write_batch_file <- function(samp_dir, base_path, exe_path, cal_path,  batch_name, out_dir){
  require(tidyverse)
  
  ## Change directory to where ascii files are located
  dir_path <- str_c(base_path, "\\", samp_dir)
  change_dir <- str_c("cd", dir_path, sep= " ")
  
  ## Run the EXE file
  #command_text <- str_c(exe_path, "--cal", cal_path, "--file", str_c("..\\", samp_file), sep= " ")
  command_text <- str_c(exe_path, "--cal", cal_path, "--file", str_c(samp_dir, ".txt"), sep= " ")
  
  
  write_lines(change_dir, path= file.path(out_dir, str_c(batch_name)), append= TRUE)
  write_lines(command_text, path= file.path(out_dir, str_c(batch_name)), append= TRUE)
  write_lines("", path= file.path(out_dir, str_c(batch_name)), append= TRUE)
}

