## Script to prepare radiometer data for use with the NOAA scripts
## to calculate remote sensed reflectance values

## KBG Sept-2019

## Load functions
source("Scripts/radiometer_noaa_format_functions.R")

## WATERBODY: ??
## SAMPLING DATE: ??

## Specify pathways
base_dir <- "Data/??"
metadata_file <- file.path(base_dir, "?.txt")
spectra_out_dir <- file.path(base_dir, "")
ascii_dir <- file.path(base_dir, "")
noaa_out_dir <- file.path(base_dir, "")



#### PROCESSING WORKFLOW BELOW ####


# Function to format metadata from Radiometer Fieldsheets
# this returns a dataframe with metadata for every file generated
# by the radiometer
# Arguments:
# file_path: the location and filename of the radiometer field data
meta_df <- format_radiometer_metadata(metadata_file_path= metadata_file)

# Exports a single text file for each pixel, site, spectra_rep
# includes metadata and files associated with that measurement
# Arguments:
# metadata_df: the data frame generated by format_radiometer_metadata
# export_path: a folder to store output (will create folder if it does not exist)
export_spectra_files(metadata_df= meta_df, 
                     export_path= spectra_out_dir)

# Function to export plots of the raw radiance values from the radiometer
# Plots are exported to the same folder as the output of export_spectra_files
# Arguments:
# spectra_path: the location of the files exported by export_spectra_files (figures are exported here too)
# ascii_path: the location of the ascii exported files from the radiometer
make_spectra_plots(spectra_path= spectra_out_dir, 
                   ascii_path= ascii_dir)


#### GO THROUGH ALL PLOTS AND FILL OUT THE THE TYPE_REP FILE
# TO DETERMINE WHICH TYPE_REPS WILL BE RETAINED FOR FURTHER ANALYSES
# SAVE THE FILE IN THE SPECTRA_OUT_DIR
# ONCE THE TEXT FILE HAS BEEN CREATED, LOAD IT INTO R BELOW


# Path to file for type_reps to keep in analyses
# (should be saved in the spectra_out_dir)
type_rep_to_keep <- readr::read_tsv(file.path(spectra_out_dir, "type_rep_keep.txt"))


# Create text files formated for the NOAA script. 
# Each file contains a column for the ascii filenames and indicates if 
# it is a plate, sky, or water measurement
# Arguments:
# metadata_df: the data frame generated by format_radiometer_metadata
# export_path: directory to place files
# keep_tr: file that specifies which type_reps should be kept for analyses
noaa_format_export(metadata_df= meta_df, 
                   export_path= noaa_out_dir, 
                   keep_tr= type_rep_to_keep)






